server:
  port: 8080

spring:
  application:
    name: graduation-server
  datasource:
    url: jdbc:mysql://localhost:3306/graduation?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

mybatis:
  typeAliasesPackage: com.min.graduation.entity
  mapperLocations: classpath:mapper/*Mapper.xml

resources:
  static-locations:
    - classpath: /webapp/
